/**
 *
 * $Id$
 */
package workflow.validation;

import org.eclipse.emf.common.util.EList;

import workflow.TaskCommunicationConfiguration;

/**
 * A sample validator interface for {@link workflow.EmittingTask}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EmittingTaskValidator {
	boolean validate();

	boolean validateProvidesPartialData(boolean value);
	boolean validateOutgoing(EList<TaskCommunicationConfiguration> value);
}
