/**
 *
 * $Id$
 */
package workflow.validation;

import org.eclipse.emf.common.util.EList;

import workflow.TaskCommunicationConfiguration;
import workflow.TaskConcurrency;
import workflow.Variable;

/**
 * A sample validator interface for {@link workflow.Task}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TaskValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateConcurrency(TaskConcurrency value);
	boolean validateImplementationFullyQualifiedName(String value);
	boolean validateImplementationEntryPoint(String value);
	boolean validateAcceptsPartialData(boolean value);
	boolean validateIncoming(EList<TaskCommunicationConfiguration> value);
	boolean validateLocals(EList<Variable> value);
}
