/**
 *
 * $Id$
 */
package workflow.validation;

import org.eclipse.emf.common.util.EList;

import workflow.EmittingTask;
import workflow.Task;

/**
 * A sample validator interface for {@link workflow.TaskCommunicationConfiguration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TaskCommunicationConfigurationValidator {
	boolean validate();

	boolean validateIncoming(EList<EmittingTask> value);
	boolean validateOutgoing(EList<Task> value);
}
