/**
 *
 * $Id$
 */
package workflow.validation;

import org.eclipse.emf.common.util.EList;

import workflow.Task;
import workflow.TaskCommunicationConfiguration;
import workflow.Variable;

/**
 * A sample validator interface for {@link workflow.Workflow}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateTasks(EList<Task> value);
	boolean validateConfigs(EList<TaskCommunicationConfiguration> value);
	boolean validateGlobals(EList<Variable> value);
}
